version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: dockerhub-flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"

  vue_frontend:
    container_name: vue_frontend
    image: node:latest
    working_dir: /app
    volumes:
      - ./vue-frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - flask_app
    command: ["/bin/sh", "-c", "npm install && npm run dev"]

  proxy:
    build: ./proxy
    ports: ['8000:80']